image:
  repository: ghcr.io/thekoma/rpodder
  tag: 2026.05.1@sha256:254037adb577782f181d4e652bdc32c3b84fd77293282fe64100ba1d01e27af3
securityContext:
  container:
    readOnlyRootFilesystem: false
cnpg:
  main:
    enabled: true
    database: rpodder
    user: rpodder
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: /health
            readiness:
              path: /health
            startup:
              path: /health
          env:
            RPODDER_DATABASE_URL:
              secretKeyRef:
                name: cnpg-main-urls
                key: std
            # Registration: open | closed | invite
            RPODDER_REGISTRATION: open
service:
  main:
    ports:
      main:
        port: 3005
        protocol: http
